"""
Challenge 2 specific utilities (KiaKio and Squared Numbers).
Generated by cfnb from Codeforces problem 2269B: https://codeforces.com/problemset/problem/2269/B

Test file format: first line = number of tests, then each test case in Codeforces input format.
Expected answers: matching *_answers.txt file, one Python literal per line.
"""

import ast
from copy import deepcopy

__all__ = ['get_input_size', 'check_solution', 'parse_tests', 'parse_samples']

MULTITEST = True
ANSWER_KIND = 'unique'
FLOAT_TOL = None


class _Reader:
    """Whitespace-token reader over Codeforces-formatted text."""

    def __init__(self, text):
        self.tokens = text.split()
        self.pos = 0

    def str(self):
        token = self.tokens[self.pos]
        self.pos += 1
        return token

    def int(self):
        return int(self.str())

    def float(self):
        return float(self.str())

    def ints(self, k):
        return [self.int() for _ in range(k)]

    def floats(self, k):
        return [self.float() for _ in range(k)]

    def strs(self, k):
        return [self.str() for _ in range(k)]

    def done(self):
        return self.pos >= len(self.tokens)


# ============================== CHALLENGE-SPECIFIC ==============================

MULTITEST = True
ANSWER_KIND = "unique"


def read_case(rd):
    n = rd.int()
    return (n, rd.ints(n))


def get_input_size(test_input):
    n, a = test_input
    return n


def to_output(result):
    return str(int(result))


# =================================== GENERIC ===================================

_RETURN_HINT = 'pairs'
_SAMPLE_EXPECTED = {
    (5, (7, 4, 16, 4, 2)): 1,
    (4, (1, 7, 10, 100)): 6,
    (3, (4, 16, 37)): 0,
    (3, (2, 20, 4)): 1,
}
_EXPECTED_BY_ID = {}
_LOADED = []
_MISSING = object()


def _key(obj):
    if isinstance(obj, (list, tuple)):
        return tuple(_key(x) for x in obj)
    return obj


def _read_cases(text, count_first=True):
    rd = _Reader(text)
    count = rd.int() if count_first else 1
    return [tuple(read_case(rd)) for _ in range(count)]


def _same_output(a, b):
    ta, tb = str(a).split(), str(b).split()
    if len(ta) != len(tb):
        return False
    for x, y in zip(ta, tb):
        if x == y:
            continue
        if FLOAT_TOL is None:
            return False
        try:
            fx, fy = float(x), float(y)
        except ValueError:
            return False
        if abs(fx - fy) > FLOAT_TOL * max(1.0, abs(fy)):
            return False
    return True


def _get_expected(test_input):
    """Return (original_input, expected_answer), or None if the input is unknown."""
    entry = _EXPECTED_BY_ID.get(id(test_input))
    if entry is not None:
        return entry
    try:
        expected = _SAMPLE_EXPECTED.get(_key(test_input), _MISSING)
    except TypeError:
        return None
    return None if expected is _MISSING else (test_input, expected)


def check_solution(test_input, result, proc, tmax, rmax):
    """
    Check a solution against the expected answer.

    Returns:
    --------
    tuple : (is_accurate, is_time_efficient, is_memory_efficient, custom_message)
        Time and memory are measured by utils.py, so both flags are always True here.
    """
    if result is None:
        return (False, True, True,
                "Invalid output: function returned None. Did you run the cell containing your solution?")
    entry = _get_expected(test_input)
    if entry is None:
        return (False, True, True,
                "Unknown test input. Did your function modify its arguments in place? Work on a copy instead.")
    original, expected = entry
    try:
        if ANSWER_KIND == 'unique':
            is_accurate = _same_output(to_output(result), to_output(expected))
        else:
            is_accurate = bool(check(deepcopy(original), result, expected))
    except Exception as e:
        return (False, True, True,
                f"Invalid output format: expected {_RETURN_HINT}, got {type(result).__name__} ({e}). "
                f"Make sure your function returns {_RETURN_HINT}.")
    return (is_accurate, True, True, None)


def parse_tests(file_path):
    """
    Parse the hidden test file and register the expected answers.

    Returns:
    --------
    list : List of tuples, each tuple being the arguments of my_solution
    """
    with open(file_path, 'r') as f:
        tests = _read_cases(f.read())
    with open(file_path.replace('_tests.txt', '_answers.txt'), 'r') as f:
        answers = [ast.literal_eval(line) for line in f.read().splitlines() if line.strip()]
    if len(answers) != len(tests):
        raise ValueError(f"{len(tests)} tests but {len(answers)} answers")
    _EXPECTED_BY_ID.clear()
    _LOADED[:] = [tests]  # keep the tuples alive so their ids stay unique
    for test, expected in zip(tests, answers):
        _EXPECTED_BY_ID[id(test)] = (deepcopy(test), expected)
    return tests


def parse_samples(sample_input):
    """
    Parse a sample input string (Codeforces format) into test cases.

    Returns:
    --------
    list : List of tuples (same format as parse_tests)
    """
    return _read_cases(sample_input, count_first=MULTITEST)
